version: "3.9"

services:
  sprint4:
    build:
      context: .
      dockerfile: Dockerfile
    image: sprint4:latest
    container_name: sprint4
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}

      APP_JWT_ISSUER: ${APP_JWT_ISSUER:-sprint4-api}
      APP_JWT_SECRET: ${APP_JWT_SECRET:sakdhjui1knosjha8dhi1on0sa9812kn318snas}
      APP_JWT_EXPIRATION_MINUTES: ${APP_JWT_EXPIRATION_MINUTES:-60}

      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:RM}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:fiap25}

      SERVER_PORT: 8080

    restart: unless-stopped
